GET {{Cardsy.API_HostAddress}}/todos/
Accept: application/json

###

GET {{Cardsy.API_HostAddress}}/todos/1
Accept: application/json

###

GET {{Cardsy.API_HostAddress}}/games/concentration
Accept: application/json

###

GET {{Cardsy.API_HostAddress}}/games/concentration/1
Accept: application/json

###

POST {{Cardsy.API_HostAddress}}/games/concentration/create
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "size": 0,
  "solution": [1,1,2,2]
}

###