@Cardsy.API_HostAddress = https://localhost:5001
###

GET {{HostAddress}}/games/concentration
Accept: application/json

###

GET {{Cardsy.API_HostAddress}}/games/concentration/search
###

GET {{HostAddress}}/games/concentration/1
Accept: application/json

###

POST {{HostAddress}}/games/concentration/create
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "size": 0,
  "solution": [1,1,2,2]
}

###

