// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Cardsy.Data.Games.Concentration;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Cardsy.Data.CompiledModels
{
    public static class ConcentrationGameUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(ConcentrationGame @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref BoardSize Size(ConcentrationGame @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Solution>k__BackingField")]
        public static extern ref int[] Solution(ConcentrationGame @this);
    }
}
