volumes:
    cardsy-db:

services:
  cardsy.api:
    volumes:
        - ./Cardsy.API/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "8080"
      
  cardsy.database:
    image: postgres:latest
    container_name: cardsy.database
    environment: 
        - POSTGRES_DB=cardsy
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=local
    volumes:
        - cardsy-db:/var/lib/postgresql/data
    ports:
        - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]


  cardsy.cache:
    image: valkey/valkey:latest
    restart: always
    ports:
        - "6379:6379"